### ISSUE TITLE
Some nodes stuck in progress

### ISSUE THREAD

**Issue by tpazderka** [nikkow/node-red-contrib-tahoma#13]
From time to time, some nodes status is stuck as in progress. It looks like the node IDs get mixed up and one node claims to finish multiple times (judging from the debugging output).

**Comment by tpazderka** [comment]
Here is some info from the logs.

```
0|node-red | TypeError: Cannot read property 'username' of undefined
0|node-red |     at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-tahoma/core/tahomalink.js:40:36)
0|node-red |     at ontimeout (timers.js:498:11)
0|node-red |     at tryOnTimeout (timers.js:323:5)
0|node-red |     at Timer.listOnTimeout (timers.js:290:5)
0|node-red | undefined
0|node-red | TypeError: Cannot read property 'statusCode' of undefined
0|node-red |     at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-tahoma/core/tahomalink.js:61:10)
0|node-red |     at self.callback (/home/pi/.node-red/node_modules/request/request.js:185:22)
0|node-red |     at emitOne (events.js:116:13)
0|node-red |     at Request.emit (events.js:211:7)
0|node-red |     at Request.onRequestError (/home/pi/.node-red/node_modules/request/request.js:877:8)
0|node-red |     at emitOne (events.js:116:13)
0|node-red |     at ClientRequest.emit (events.js:211:7)
0|node-red |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
0|node-red |     at emitOne (events.js:116:13)
0|node-red |     at TLSSocket.emit (events.js:211:7)
0|node-red | undefined
```

**Comment by nikkow** [comment]
This issue is most likely related to the changes that occurred on the (unofficial) Somfy API used in the v1 of this project.

I just released the v2, using the new API, officially available for third-party software like this one.

The issue you encountered should be fixed by upgrading the plugin to v2 (either through the command `npm i node-red-contrib-tahoma@2.0.0` in your `.node-red` install folder, or using the plugin palette)

However, please note that you will have to reconfigure the link between this module and your Tahoma box. Please read the read-me file and let me know if anything remains unclear.
