### ISSUE TITLE
Device list is empty

### ISSUE THREAD

**Issue by gon0** [nikkow/node-red-contrib-tahoma#19]
Hello, 

thank you for this great node. After first installation, I could choose one of my devices from the drop-down box.
Now, after some months, I wanted to use other devices. The device-box is empty. How do I reload and display the devices-list (see screenshot)?

![2020-02-23 11_05_39-Window](https://user-images.githubusercontent.com/33236024/75110324-12f84900-562d-11ea-9a6c-6c1b3ceb81cc.png)

**Comment by hogheg** [comment]
I'm facing the same problem during a clean installation on windows 10. Device-box is empty. Above I can choose from 3 identical copies of my tahoma-box, after several attempts. Cleaning cache and removing /reinstalling your contrib makes no difference. 
velux integra roof-windows and somfy screens. would love to get this "missing link". 
Maybe optimistic to run this in Windows?

**Comment by nikkow** [comment]
Thanks for your report!

@hogheg, the issue you are encountering might not be related to the platform you installed the plugin on :)

This issue is most likely related to the changes that occurred on the (unofficial) Somfy API used in the v1 of this project.

I just released the v2, using the new API, officially available for third-party software like this one.

The issue you encountered should be fixed by upgrading the plugin to v2 (either through the command `npm i node-red-contrib-tahoma@2.0.0` in your `.node-red` install folder, or using the plugin palette)

However, please note that you will have to reconfigure the link between this module and your Tahoma box. Please read the read-me file and let me know if anything remains unclear.

**Comment by Programmierfreund** [comment]
Thank you very much for your work - I appreciate that. Your v2 is not available via the plugin palette yet. I will wait until you deploy it there because I avoid using npm inside a preconfigured docker environment.
Best regards
