### ISSUE TITLE
Does this node require an internet connection?

### ISSUE THREAD

**Issue by ozdeadmeat** [nikkow/node-red-contrib-tahoma#51]
I understand that I will need to have an internet connection for setup of the API key etc. But does it require an internet connection to function?

**Comment by nikkow** [comment]
Hello @ozdeadmeat,

For the moment, yes. However, due to the recent announcements from Somfy about the deployment of the **local API**, the future versions should not require an Internet connection after the setup phase. The Tahoma box will need to be on the same network than your node-red instance though. 

Best,
N.
